### ISSUE TITLE
Doesn't send flaky tests when using Playwright sharding

### ISSUE THREAD

**Issue by marhyn** [ctrf-io/slack-test-reporter#1]
### Description
I am using [sharding](https://playwright.dev/docs/test-sharding#merging-reports-from-multiple-shards) for playwright tests with the blob reporter. Then I merge those blob reports with `playwright-ctrf-json-reporter` reporter and try to send the merged report, which is now ctrf compliable. But only the `results` call works, not the `flaky` one.
I am using the report merger according to the [Playwright docs](https://playwright.dev/docs/test-sharding#merging-reports-from-multiple-shards).

### Commands
Playwright report merge:
`npx playwright merge-reports --reporter playwright-ctrf-json-reporter ./all-blob-reports`

Slack-ctrf send flaky tests:
`SLACK_WEBHOOK_URL=WEBHOOK_URL npx slack-ctrf flaky ctrf/ctrf-report.json`

### Versions

- Node 20.9.
- PNPM 9.2.0

### Generated ctrf report
[ctrf-report.json](https://github.com/user-attachments/files/15896938/ctrf-report.json)

**Comment by Ma11hewThomas** [comment]
Thanks, fixed in v0.0.10
