### ISSUE TITLE
Possibility to use plugin for MatterMost

### ISSUE THREAD

**Issue by bdimitrovski** [ctrf-io/slack-test-reporter#2]
I came here after looking at different different Cypress test reporters for communications tools, and even building my own, which looks something like this:

<img width="580" alt="Screenshot 2024-07-17 at 10 41 24" src="https://github.com/user-attachments/assets/78c8a57f-c2ff-4d7b-8054-ea3a5c249f5c">

but this is for [MatterMost](https://mattermost.com/) 

However, I am interested if I could make slack-ctrf work for MatterMost too, as it really seems to outline the most important metrics for my tests, which I could also combine with other information that I already use.

From what I can tell, the only difference might be the message formatting, and replacing the incoming webhook with a MM one.

**Comment by Ma11hewThomas** [comment]
A MatterMost plug-in is a great idea, it will be published separately to the slack plugin. Please can you add a post to ctrf discussions with a plug-in request and we'll discuss further - https://github.com/orgs/ctrf-io/discussions

**Comment by bdimitrovski** [comment]
> A MatterMost plug-in is a great idea, it will be published separately to the slack plugin. Please can you add a post to ctrf discussions with a plug-in request and we'll discuss further - https://github.com/orgs/ctrf-io/discussions

Great, glad to hear that! I will write a post there in the discussions, and please let me know if you need any help with making the plugin happen.
