### ISSUE TITLE
Duration is not calculated correctly with Jest

### ISSUE THREAD

**Issue by juanmspoleti** [ctrf-io/slack-test-reporter#3]
### Context
I'm using this library together with https://github.com/ctrf-io/jest-ctrf-json-reporter but the suite duration is not being calculated correctly, it adds a lot of more minutes to the total.

### Screenshots
It shows a total of 15 minutes in Slack
![image](https://github.com/user-attachments/assets/97c452ad-4771-4218-b270-6f622b480ff7)

Log in pipeline says it took 56 seconds (I checked the generated JSON as well)
![image](https://github.com/user-attachments/assets/6a03e4c5-720a-4441-9b32-82312c20f67f)

### Expected result
Duration in slack is the same as the duration on the generated JSON report.

**Comment by juanmspoleti** [comment]
I will also like to ask about the warning message "Missing environment properties: buildName, buildNumber, buildUrl"
Adding buildUrl sounds good, but adding buildName and buildNumber, I dont see any change in the Slack report, so it feels I added them for nothing.
![image](https://github.com/user-attachments/assets/df473976-f79e-493d-bc3c-f281da9f248c)

FYI Excellent work with this plugin!

**Comment by Ma11hewThomas** [comment]
fixed by #4, published v0.0.11

**Comment by Ma11hewThomas** [comment]
Thanks!
buildName and buildNumber are used to construct the build text, in the above image buildName is _Execution of all tests_ and buildNumber is _17._ buildUrl is used to create a link. We can't extract this information from buildUrl as build tools differ.

**Comment by juanmspoleti** [comment]
> Thanks! buildName and buildNumber are used to construct the build text, in the above image buildName is _Execution of all tests_ and buildNumber is _17._ buildUrl is used to create a link. We can't extract this information from buildUrl as build tools differ.

Oh you are right, perfect, thanks!
