### ISSUE TITLE
[QUESTION] Ability to change title of the mesage

### ISSUE THREAD

**Issue by mfidalgo-RatedPower** [ctrf-io/slack-test-reporter#6]
Hi there,
thanks a lot for this work, I think it is a great idea!
I was able to generate a ctrf report and send a Slack message but I was wondering if the title could be changed somehow.
In our pipeline, we run different types of tests: unit, e2e, api, etc so it would be ideal to have the type of test as title and not just "CTRF Test Results" because it makes it more difficult to understand
![image](https://github.com/user-attachments/assets/3bc1f87e-19ad-4075-ae23-f82f29640286)

**Comment by Ma11hewThomas** [comment]
Agreed, this is a useful feature to have. 

Released in v0.0.12

**Comment by mfidalgo-RatedPower** [comment]
wow! thanks a lot!
